INSERT INTO setting(id, label, key, value_type,  is_deleted, created_on, created_by, is_editable, is_global, is_user, is_business, is_user_business, description, enum_id) VALUES(uuid_generate_v4(), 'Time Zone', 'time_zone', 'string', false, CURRENT_TIMESTAMP,  '00000000-0000-0000-0000-000000000000', true, true, true, true, true, null, 'bf5195d6-a5d0-4899-b7d5-faa16b09a209');
INSERT INTO setting(id, label, key, value_type,  is_deleted, created_on, created_by, is_editable, is_global, is_user, is_business, is_user_business, description) VALUES(uuid_generate_v4(), 'Email App Password', 'email_app_password', 'string', false, CURRENT_TIMESTAMP,  '00000000-0000-0000-0000-000000000000', true, false, true, false, 'App password for personal email. This is used to send emails from the application.');
INSERT INTO setting(id, label, key, value_type,  is_deleted, created_on, created_by, is_editable, is_global, is_user, is_business, is_user_business, description) VALUES(uuid_generate_v4(), 'Financial Year Start', 'financial_year_start', 'date_time', false, CURRENT_TIMESTAMP,  '00000000-0000-0000-0000-000000000000', true, true, false, false, null);

INSERT INTO setting(id, label, key, value_type,  is_deleted, created_on, created_by, is_editable, is_global, is_user, is_business, is_user_business, description) VALUES(uuid_generate_v4(), 'Leave Request Template', 'leave_request_template', 'text', false, CURRENT_TIMESTAMP,  '00000000-0000-0000-0000-000000000000', true, true, false, false, null);
INSERT INTO setting(id, label, key, value_type,  is_deleted, created_on, created_by, is_editable, is_global, is_user, is_business, is_user_business, description) VALUES(uuid_generate_v4(), 'Leave Request Status Update Template', 'leave_request_status_update_template', 'text', false, CURRENT_TIMESTAMP,  '00000000-0000-0000-0000-000000000000', true, true, false, false, null);
INSERT INTO setting(id, label, key, value_type,  is_deleted, created_on, created_by, is_editable, is_global, is_user, is_business, is_user_business, description) VALUES(uuid_generate_v4(), 'Email OTP template', 'email_otp_template', 'text', false, CURRENT_TIMESTAMP,  '00000000-0000-0000-0000-000000000000', true, true, false, false, null);

INSERT INTO setting(id, label, key, value_type,  is_deleted, created_on, created_by, is_editable, is_global, is_user, is_business, is_user_business, description) VALUES(uuid_generate_v4(), 'Unpaid Leave Count', 'unpaid_leave_count', 'integer', false, CURRENT_TIMESTAMP,  '00000000-0000-0000-0000-000000000000', false, false, false, true, false, null);
INSERT INTO setting(id, label, key, value_type,  is_deleted, created_on, created_by, is_editable, is_global, is_user, is_business, is_user_business, description) VALUES(uuid_generate_v4(), 'Total Common Leave Count', 'total_common_leave_count', 'integer', false, CURRENT_TIMESTAMP,  '00000000-0000-0000-0000-000000000000', false, false, false, true, false, null);
INSERT INTO setting(id, label, key, value_type,  is_deleted, created_on, created_by, is_editable, is_global, is_user, is_business, is_user_business, description) VALUES(uuid_generate_v4(), 'Total Restricted Leave Count', 'total_restricted_leave_count', 'integer', false, CURRENT_TIMESTAMP,  '00000000-0000-0000-0000-000000000000', false, false, false, true, false, null);
INSERT INTO setting(id, label, key, value_type,  is_deleted, created_on, created_by, is_editable, is_global, is_user, is_business, is_user_business, description) VALUES(uuid_generate_v4(), 'Total Medical Leave Count', 'total_medical_leave_count', 'integer', false, CURRENT_TIMESTAMP,  '00000000-0000-0000-0000-000000000000', false, false, false, true, false,  null);
INSERT INTO setting(id, label, key, value_type,  is_deleted, created_on, created_by, is_editable, is_global, is_user, is_business, is_user_business, description) VALUES(uuid_generate_v4(), 'Total Casual Leave Count', 'total_casual_leave_count', 'integer', false, CURRENT_TIMESTAMP,  '00000000-0000-0000-0000-000000000000', false, false, false, true, false, null);
